---
version: 2
plan:
  project-key: ADGEXT
  key: DARELEASESPECS
  name: disable-amp - build release

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            docker build \
              --file Dockerfile \
              --progress plain \
              --target build-release-output \
              --output type=local,dest=output \
              .
    - inject-variables:
        file: output/artifacts/variables.txt
        scope: RESULT
        namespace: userscriptMeta
#     - any-task:
#         plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
#         configuration:
#           selectedRepository: defaultRepository
#           tagName: v${bamboo.userscriptMeta.version}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ./bamboo-specs/scripts/cleanup.sh "output/artifacts/disable-amp.meta.js,output/artifacts/disable-amp.user.js"
  artifacts:
    - name: disable-amp.meta.js
      location: output/artifacts
      pattern: disable-amp.meta.js
      shared: 'true'
      required: 'true'
    - name: disable-amp.user.js
      location: output/artifacts
      pattern: disable-amp.user.js
      shared: 'true'
      required: 'true'
  requirements:
    - extension: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: []
other:
  concurrent-build-plugin: system-default
