---
version: 2
plan:
  project-key: ADGEXT
  key: DAINCRSPECS
  name: disable-amp - increment version
variables:
  dockerNode: node:current-alpine3.12

stages:
  - Increment:
      manual: 'false'
      final: 'false'
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${bamboo.tmp.directory}/yarn: /usr/local/share/.cache/yarn/v6
    docker-run-arguments:
      - --net=host
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -alt
            yarn install
            yarn increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
