---
version: 2
plan:
  project-key: ADGEXT
  key: DATESTSPECS
  name: disable-amp - test

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            docker build \
              --file Dockerfile \
              --progress plain \
              --target test-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ./bamboo-specs/scripts/cleanup.sh "output/artifacts/disable-amp.meta.js,output/artifacts/disable-amp.user.js"
  artifacts:
    - name: disable-amp.meta.js
      location: output/artifacts
      pattern: disable-amp.meta.js
      shared: 'true'
      required: 'true'
    - name: disable-amp.user.js
      location: output/artifacts
      pattern: disable-amp.user.js
      shared: 'true'
      required: 'true'
  requirements:
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
