---
version: 2
plan:
  project-key: ADGEXT
  key: DATESTSPECS
  name: disable-amp - test specs
variables:
  dockerNode: node:current-alpine3.12

stages:
  - Test:
      manual: 'false'
      final: 'false'
      jobs:
        - Test

Test:
  key: TEST
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${bamboo.tmp.directory}/yarn: /usr/local/share/.cache/yarn/v6
    docker-run-arguments:
      - --net=host
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -alt
            yarn install
            yarn dev
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
